name: Download latest Flutter Status from dev.to

on:
  workflow_dispatch:
  schedule:
    - cron: 1 8 * * *

jobs:
  downloadStatus:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.DISCORD_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js version 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - run: npm start
    - run: |
        git config user.name kenriortega
        git config user.email kenriortega@gmail.com
        git add .
        git commit -m "Add articles for today"
        git push
